#!/bin/bash

brewlist="oh-my-posh unison bat fzf fd eza delta zoxide nvim zsh-autosuggestions zsh-syntax-highlighting ghostty kitty ripgrepi fortune qlmarkdown"

for i in $brewlist
do
  brew install "$i"
done

echo "vi Library/Application\ Support/com.mitchellh.ghostty/config"
