#!/bin/sh

cmd='cp -p'
if [ x$1 == x-mv ]; then
	cmd=mv
	shift
fi

aD() {
fil=${1/\//}

if [ x == ${fil}x ] ; then exit
fi

d=$(date +%y%m%d)

fild=${fil//.*/}-$(date +%y%m%d_%H%M%S).${fil//*./}


${cmd} $fil $fild

}

for i in $*
do
	aD $i
done
