#!/bin/bash

MAX_N=29
cdnlfile=~/.cdnumlist

for i in {1..$MAX_N}; do
	eval cdnum_item${i}=$HOME
done

scan_cd_list() {
	source $cdnlfile
}


print_cd_list() {
	cdnlfile=~/.cdnumlist
	rm -f $cdnlfile
	for i in {1..$MAX_N}; do
		eval echo "cdnum_item${i}="'$'"cdnum_item${i}" >> $cdnlfile
	done
}

for i in {1..$MAX_N}; do
	alias sd${i}='cdnum_item'${i}'=$PWD;print_cd_list'
	alias cd${i}='scan_cd_list;cd $cdnum_item'${i}'; echo $PWD'
done

alias cdx='scan_cd_list; for i in {1..'$MAX_N'}; do eval echo \$cdnum_item${i}; done  | cat -n'

scan_cd_list
print_cd_list
