#!/bin/bash

# copy whole directory tree to a new place
#
# cpDir target

function fund {
    for i in $(find . -type d)
    do
	echo mkdir -p $target/$i
	mkdir -p $target/$i
    done
}

function funf {
    for i in $(find . -type f)
    do
	echo cp -p  $i $target/$i
	cp -p  $i $target/$i
    done
}


if [ $# == 1 ]; then

target=$1

fund
funf

fi

exit 0
