#!/bin/bash
f=$1
shift

emitstatTotal=0

function emitstat {
	if [ $1 != 0 ]; then echo "[00;31m############################ ERROR $1 ############################[00m";  fi
}

red='[01;31m'
green='[01;32m'
blue='[01;34m'
black='[00m'
acol=$green

a=1
n="$(echo $f | wc -w | pr1)"
eb="==========================================="
es="====================="
e=$eb

for i in $f
do
    t="$(printf '%30s' $i)"
    t2="$(printf '%30s' sample)"
    t2s="$(printf '%74s' $i)"
    t2b="$(printf '%30s' $i)"

    l=$(echo "$t"|tr ' ' '.'|wc -c)
    l2=$(echo "$t2"|tr ' ' '.'|wc -c)

    if [ $l == $l2 ]; then e=$eb; t=$t2b; else e=$es; t=$t2s; fi

    echo "${blue}($e: $t :$e) ${acol}$((a++))${black} ($((n - a + 1)) $n)"
    (cd $i && eval "$@" ; exit $?) ; zz=$?; emitstat $zz ; if [ $zz != 0 ]; then acol=$red; elist="$elist $red$((a-1))${black}:$blue$i$black"; emitstatTotal="$((emitstatTotal+1))"; say error $emitstatTotal;fi
done

if [ $emitstatTotal != 0 ]; then echo "[01;31mTotal error:[00m" $emitstatTotal "($((a-1))) $elist"; say $emitstatTotal bad; fi
