#!/bin/sh

# linkFname charsA charsB
# change all charsA to charsB of all matching files

if [ $# != 2 ]; then
	echo usage: $0 from to
	exit 1
fi

\ls | grep $1 | sed "s/\(.*\)\($1\)\(.*\)/ln \1\2\3 \1$2\3/"
