#!/bin/bash
 
#
# grep for multiple expressions giving each its own color (max 6)
# It only works for stdin
#
# execute "raingrep" to get a list of the predefined colors
#
# raingrep -a print all lines even if no regexp match is found
#
 
function raingrep {
        cat \
        | GREP_COLOR="01;34" grep --color=always -e "$1" -e $ \
        | GREP_COLOR="01;32" grep --color=always -e "$2" -e $ \
        | GREP_COLOR="01;31" grep --color=always -e "$3" -e $ \
        | GREP_COLOR="01;35" grep --color=always -e "$4" -e $ \
        | GREP_COLOR="01;36" grep --color=always -e "$5" -e $ \
        | GREP_COLOR="01;33" grep --color=always -e "$6" -e $ \
        | cat
}
 
if [ $# == 0 ]; then
        echo  -n raingrep '[-a] '
        echo blue green red magenta cyan yellow | raingrep blue green red magenta cyan yellow
        exit 1
fi
 
if [ x$1 == x-a ]; then
        shift
  raingrep "$1" "$2" "$3" "$4" "$5" "$6"
        exit 0
fi
 
grep -e "${1:-zxcxxzczxcxcxxzc$RANDOM}" -e "${2:-zxcxxzczxcxcxxzc$RANDOM}" -e "${3:-zxcxxzczxcxcxxzc$RANDOM}" -e "${4:-zxcxxzczxcxcxxzc$RANDOM}" -e "${5:-zxcxxzczxcxcxxzc$RANDOM}" -e "${6:-zxcxxzczxcxcxxzc$RANDOM}" \
        | raingrep "$1" "$2" "$3" "$4" "$5" "$6"
