#!/bin/bash

function fix {
	for fil in *
	do

		if [ -d $fil ]; then 
			echo fixx dir $fil
			chmod o-w $fil
			( echo cd $fil; cd $fil; fixx );
		fi

		if [ -f $fil ];	then
			echo fixx file $fil
			chmod o-w,a-x $fil
		fi
	done
}

if [ $# = 0 ]; then fix
               else for dir
		    do
			if [ -d $dir ]; then ( echo cd $dir
                                               cd $dir
					       fixx )
			fi
		    done
fi
